version = '2'

[run]
  allow-parallel-runners = true
  tests                  = false

[linters]
  default = 'all'
  disable = [
    'depguard',
    'err113',
    'exhaustruct',
    'forbidigo',
    'gochecknoinits',
    'gosec',
    'noinlineerr',
    'prealloc',
    'tagalign',
    'tagliatelle',
    'varnamelen',
  ]

  [linters.settings]
    [linters.settings.nlreturn]
      block-size = 2

    [linters.settings.tagliatelle]
      [linters.settings.tagliatelle.case]
        [linters.settings.tagliatelle.case.rules]
          toml = 'snake'

  [linters.exclusions]
    generated = 'lax'
    paths = ['builtin$', 'examples$', 'third_party$']
    presets = [
      'comments',
      'common-false-positives',
      'legacy',
      'std-error-handling',
    ]

[formatters]
  enable = ['gci', 'gofmt', 'gofumpt', 'goimports']

  [formatters.exclusions]
    generated = 'lax'
    paths     = ['builtin$', 'examples$', 'third_party$']
